require_relative "skeleton"
require_relative "chop_words"
require_relative "double_letters"
require_relative "remove_newlines"
require_relative "remove_spaces"
require_relative "shake_words"
require_relative "shuffle_words"
require_relative "sprinkle_numbers"
